# Iac Scanner Configuration File

blacklisted_strings: [] # skip matches containing any of these strings (case sensitive)
blacklisted_extensions: [ ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".psd", ".xcf", ".zip", ".tar.gz", ".ttf", ".lock"] 
# need to confirm as windows hides file extensions
blacklisted_paths: ["{sep}var{sep}lib{sep}docker", "{sep}var{sep}lib{sep}containerd", "{sep}bin", "{sep}boot", "{sep}dev", "{sep}lib", "{sep}lib64", "{sep}media", "{sep}proc", "{sep}run", "{sep}sbin", "{sep}usr{sep}lib", "{sep}sys"] # use {sep} for the OS' path seperator (i.e. / or \)
 

report: spyre.log
evidence-collector:
  # disabled: true
  # default: spyre_$hostname_$datetime.zip
  file: spyre.zip
  password: infected
  max-size: 1G
# hostname: some-random-host
# max-file-size: 32M
# proc-ignore-names: ["chrome.exe"]
# paths: ["D:\\"]
# high-priority: true